# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0008_auto_20170415_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Description par defaut', max_length=200, null=True)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.Objet')),
            ],
        ),
    ]
